name: "Release"

on:
  push:
    branches:
      - "master"
jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'patch version bump ')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: "Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
          commit-message: 'patch version bump {{version}} [ci skip]'
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
